import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Eye, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { PageHeader, Status, EmptyState } from '../../components/common/Ui';
import { createVehicleApi, deleteVehicleApi, getVehiclesApi, updateVehicleApi } from '../../services/businessApi';
import { formatCurrencyPKR } from '../../utils/formatters';

const emptyVehicle = { make: '', model: '', variant: '', year: new Date().getFullYear(), sellingPrice: 0, purchaseRate: 0, stock: 1, status: 'AVAILABLE', fuel: 'Petrol', transmission: 'Automatic', colors: ['Black', 'White'], images: [] };

export default function CarsApi() {
  const [vehicles, setVehicles] = useState([]); const [query, setQuery] = useState(''); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = () => getVehiclesApi().then(setVehicles).catch(requestError => setError(requestError.response?.data?.message || 'Unable to load vehicles.'));
  useEffect(() => { load(); }, []);
  const save = async (event) => { event.preventDefault(); try { const payload = { ...editing, year: Number(editing.year), sellingPrice: Number(editing.sellingPrice), purchaseRate: Number(editing.purchaseRate), stock: Number(editing.stock) }; if (editing.id) await updateVehicleApi(editing.id, payload); else await createVehicleApi(payload); setEditing(null); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to save vehicle.'); } };
  const remove = async (id) => { if (!window.confirm('Delete this vehicle?')) return; try { await deleteVehicleApi(id); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to delete vehicle.'); } };
  const filtered = vehicles.filter(vehicle => `${vehicle.legacyId} ${vehicle.make} ${vehicle.model} ${vehicle.variant}`.toLowerCase().includes(query.toLowerCase()));
  return <><PageHeader title="Cars" text="Manage database-backed inventory, pricing, stock, and status." action={<button className="primary" onClick={() => setEditing(emptyVehicle)}><Plus size={16} /> Add vehicle</button>} /><div className="toolbar"><div className="search"><Search size={16} /><input placeholder="Search vehicles" value={query} onChange={event => setQuery(event.target.value)} /></div></div>{error && <div className="error" role="alert">{error}</div>}{editing && <form className="panel form" onSubmit={save}><h3>{editing.id ? 'Edit vehicle' : 'New vehicle'}</h3><div className="form-grid">{['make', 'model', 'variant', 'year', 'purchaseRate', 'sellingPrice', 'stock', 'fuel', 'transmission'].map(field => <label key={field}>{field}<input required={['make', 'model', 'variant'].includes(field)} type={['year', 'purchaseRate', 'sellingPrice', 'stock'].includes(field) ? 'number' : 'text'} value={editing[field] ?? ''} onChange={event => setEditing({ ...editing, [field]: event.target.value })} /></label>)}<label>Status<select value={editing.status} onChange={event => setEditing({ ...editing, status: event.target.value })}><option>AVAILABLE</option><option>RESERVED</option><option>SOLD</option><option>INACTIVE</option></select></label></div><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button> <button className="primary">Save vehicle</button></form>}{!filtered.length ? <section className="panel"><EmptyState text="No vehicles found." /></section> : <section className="panel table"><table><thead><tr><th>Vehicle</th><th>Year</th><th>Price</th><th>Stock</th><th>Status</th><th /></tr></thead><tbody>{filtered.map(vehicle => <tr key={vehicle.id}><td><b>{vehicle.make} {vehicle.model}</b><small>{vehicle.variant} · {vehicle.legacyId}</small></td><td>{vehicle.year}</td><td>{formatCurrencyPKR(vehicle.sellingPrice)}</td><td>{vehicle.stock}</td><td><Status value={vehicle.status} /></td><td className="actions"><Link to={`/showroom/${vehicle.legacyId}`}><Eye size={16} /></Link><button onClick={() => setEditing(vehicle)}><Pencil size={16} /></button><button onClick={() => remove(vehicle.id)}><Trash2 size={16} /></button></td></tr>)}</tbody></table></section>}</>;
}
